#!/usr/bin/bash

declare -a nwsvc=("networking.service" "NetworkManager.service" "systemd-networkd.service")

# $ systemctl show NetworkManager.service --property=ActiveState,UnitFileState
#   ActiveState=active
#   UnitFileState=enabled

echo -en "Network Svc:\tactive & enabled: "
for i in 0 1 2; do
    readarray -t prpty < <(systemctl show ${nwsvc[i]} --property=ActiveState,UnitFileState | cut -d "=" -f 2)
    if [[ ${prpty[0]} = "active" && ${prpty[1]} = "enabled" ]]; then
        echo -n "\"${nwsvc[i]}\" "
    fi
done
echo " "

#string1=$(systemctl list-units --all | grep -Ei 'networking\.|NetworkManager\.|networkd\.' | grep 'service' | grep -E 'running')
#string2=$(systemctl list-units --all | grep -Ei 'networking\.|NetworkManager\.|networkd\.' | grep 'service' | grep -Ev 'dead')
#if [ -n "$string1" ]; then
#    echo -e "Network Svc:\trun: systemctl status ${string1:2:24}"
#else
#    echo -e "Network Svc:\trun: systemctl status ${string2:2:20}"
#fi
