#!/bin/sh

# old shit - ignore
# echo "Updated backup image: /mnt/SynologyNAS/rpi_share/raspberrypi4b/$(ls -l /mnt/SynologyNAS/rpi_share/raspberrypi4b | tail -1)"

tail -3 /home/pi/imagebackup.log | head -1
