#!/usr/bin/env sh

# This script needs to change as updates are now handled in a different manner!
# The following command may be helpful:
# diff -q -x .git -x diffs -x README.md ~/RonR-RPi-image-utils/ /mnt/SynologyNAS/rpi_share/img-utils/ | wc -l

if [ $(find /home/pi -name 'Z______IMAGE_UTILS_UPDATED______Z') ]; then
  echo "image-utils has been UPDATED!"
fi


# if [[ -n $(find /home/pi -name "Z______IMAGE_UTILS_UPDATED______Z") ]]; then
#   echo "There has been an update to image-utils!"
# fi

